baseurl = "/"
title = "小猪的笔记"
languageCode = "zh-cn"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Disqus 评论系统的 shortname，用于启用评论功能。
googleAnalytics = "" # 谷歌分析跟踪 ID，用于启用谷歌分析功能。

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[Params]
 
  toc = true # Enable Table of Contents
  schema = true # Enable Schema
  searchEnabled = false
  description = "记录笔记" # Description of your site
  opengraph = false    #是否启用 Open Graph 标签。
  readmore = false # 是否在文章列表中显示“阅读更多”按钮。
  authorbox = false #是否在文章页面中显示作者信息框。
  pager = true #是否启用翻页功能。
  post_meta = ["date", "categories"] # 文章元数据的显示顺序
  mainSections = ["post", "docs"] #主要文章分类。

  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
[Params.logo] # 网站 Logo 相关设置。
  subtitle = "个人博客" # Logo subtitle

[Params.sidebar] #侧边栏相关设置。
  home = "right"   #  首页侧边栏布局
  list = "left"   # 列表页侧边栏布局
  single = "right"   # 单篇文章页侧边栏布局。
  # 侧边栏小工具的显示顺序。
  widgets = ["recent", "categories", "taglist","social"]

[Params.widgets] #侧边栏小工具相关设置。
  recent_num = 5 # 最近文章小工具中显示的文章数量
  tags_counter = true # 是否在标签列表小工具中显示每个标签对应的文章数量。

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color